import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  actionRow: {
    borderBottomColor: '#eceff1',
    borderBottomWidth: 1,
    paddingVertical: 18,
  },
  actionText: {
    color: '#202124',
    fontSize: 18,
    fontWeight: '600',
  },
  appHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  attachButton: {
    backgroundColor: 'rgba(255,255,255,0.48)',
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  attachButtonText: {
    color: '#303134',
    fontSize: 12,
    fontWeight: '600',
  },
  attachmentAction: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.44)',
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  attachmentLabel: {
    color: '#3c4043',
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
  },
  attachmentRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  authPanel: {
    gap: 12,
    padding: 24,
    width: '100%',
  },
  authScreen: {
    backgroundColor: '#fff',
    flex: 1,
    justifyContent: 'center',
  },
  authTitle: {
    color: '#202124',
    fontSize: 28,
    fontWeight: '700',
    marginBottom: 8,
  },
  backButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 28,
  },
  backButtonText: {
    color: '#3c4043',
    fontSize: 34,
  },
  boardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 18,
    paddingTop: 18,
  },
  boardSubtitle: {
    color: '#6f7478',
    fontSize: 13,
    marginTop: 2,
  },
  boardTitle: {
    color: '#202124',
    fontSize: 28,
    fontWeight: '700',
  },
  brand: {
    color: '#202124',
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0,
  },
  cardBody: {
    color: '#3c4043',
    fontSize: 15,
    lineHeight: 21,
    marginTop: 10,
  },
  cardMeta: {
    color: '#5f6368',
    fontSize: 12,
    marginTop: 10,
  },
  cardTitle: {
    color: '#202124',
    flex: 1,
    fontSize: 20,
    fontWeight: '700',
  },
  cardTitleRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 8,
  },
  chip: {
    borderColor: '#dfe3e7',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  chipText: {
    color: '#3c4043',
    fontSize: 14,
    fontWeight: '600',
  },
  disabled: {
    opacity: 0.6,
  },
  drawerBackdrop: {
    backgroundColor: 'rgba(32,33,36,0.28)',
    flex: 1,
  },
  drawerEmpty: {
    color: '#6f7478',
    fontSize: 15,
    marginTop: 18,
  },
  drawerPanel: {
    backgroundColor: '#fff',
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 52,
    width: '78%',
  },
  drawerTitle: {
    color: '#202124',
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 14,
  },
  emptyState: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 32,
  },
  emptyText: {
    color: '#6f7478',
    fontSize: 16,
    textAlign: 'center',
  },
  fab: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 32,
    bottom: 24,
    elevation: 5,
    height: 64,
    justifyContent: 'center',
    position: 'absolute',
    right: 24,
    shadowColor: '#000',
    shadowOffset: { height: 3, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 8,
    width: 64,
  },
  fabText: {
    color: '#4285F4',
    fontSize: 38,
    lineHeight: 42,
  },
  formActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  formSubmit: {
    flex: 1,
  },
  gridContent: {
    paddingBottom: 112,
    paddingHorizontal: 12,
    paddingTop: 16,
  },
  gridRow: {
    alignItems: 'flex-start',
  },
  iconButton: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 38,
  },
  iconText: {
    color: '#5f6368',
    fontSize: 26,
  },
  input: {
    backgroundColor: '#fff',
    borderColor: '#dfe3e7',
    borderRadius: 8,
    borderWidth: 1,
    color: '#202124',
    fontSize: 16,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  keepCard: {
    borderRadius: 8,
    flex: 1,
    margin: 6,
    minHeight: 132,
    padding: 16,
  },
  linkButton: {
    alignItems: 'center',
    paddingVertical: 12,
  },
  linkText: {
    color: '#2f6f55',
    fontSize: 15,
    fontWeight: '600',
  },
  loadingStrip: {
    alignItems: 'center',
    paddingTop: 8,
  },
  modalBackdrop: {
    backgroundColor: 'rgba(32,33,36,0.28)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalPanel: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    gap: 12,
    padding: 20,
  },
  modalTitle: {
    color: '#202124',
    fontSize: 22,
    fontWeight: '700',
    marginBottom: 4,
  },
  noteFooter: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  pinButton: {
    alignItems: 'center',
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  pinText: {
    color: '#3c4043',
    fontSize: 20,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#202124',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  screen: {
    backgroundColor: '#fff',
    flex: 1,
  },
  searchInput: {
    backgroundColor: '#fff',
    borderColor: '#eceff1',
    borderRadius: 8,
    borderWidth: 1,
    color: '#202124',
    elevation: 2,
    flex: 1,
    fontSize: 18,
    height: 52,
    paddingHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { height: 1, width: 0 },
    shadowOpacity: 0.12,
    shadowRadius: 3,
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: '#dfe3e7',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
  },
  secondaryButtonText: {
    color: '#3c4043',
    fontSize: 16,
    fontWeight: '700',
  },
  selectedChip: {
    backgroundColor: '#202124',
    borderColor: '#202124',
  },
  selectedChipText: {
    color: '#fff',
  },
  studentChips: {
    flexDirection: 'row',
    gap: 8,
    paddingBottom: 4,
  },
  studentMeta: {
    color: '#80868b',
    fontSize: 12,
    marginTop: 3,
  },
  studentName: {
    color: '#202124',
    fontSize: 17,
    fontWeight: '600',
  },
  studentRow: {
    borderBottomColor: '#eceff1',
    borderBottomWidth: 1,
    paddingVertical: 15,
  },
  textArea: {
    minHeight: 112,
    paddingTop: 12,
    textAlignVertical: 'top',
  },
});
